# Data Wrangling

When we collect data in the lab we often feel that any changes, or manipulations, to the data would be dishonest. However, the truth is that most data requires some manipulation as part of its analysis.  

## Find and Replace Function

The find and replace function is useful if you need to find data in your Excel sheet. This is relevant when using the air quality data from the NAPS program as instruments will report a -999 value when data wasn't collected or there was a quality control issue. If you have -999 values in your dataset you will need to find and remove it before proceeding as it will interfere with your analysis and visualization. To do this you can enter ‘-999’ in the search bar at the top right of the screen and then delete any of these values manually leaving a blank cell behind. Alternatively, if you would like to get Excel to do this work for you, you can select EDIT on the top menu, then select FIND and then REPLACE… In the FIND WHAT: box in the FIND AND REPLACE dialog box input ‘-999’ and leave the REPLACE WITH: box empty. Then click REPLACE ALL and Excel will replace all the ‘-999’ values with blank cells and tell you how many instances the -999 value was replaced. If you have a plot already created from this data it should be updated automatically.

Replacing the -999 values with blanks will not work if you need to use those values in a calculation, such as the calculation of Ox. To fix this issue you will need to remove any rows with missing data. To do this, highlight all the columns involved (likely A-E in this example), select the EDIT menu, then FIND, and GO TO. In the GO TO dialog box click on SPECIAL. In the GO TO SPECIAL dialog box select BLANKS, then click OK. This will highlight any cells that are blank in the columns you highlighted. You can remove the rows manually by right clicking on the row number and selecting DELETE from the dropdown menu.  Alternatively, with the blank cells highlighted, you can select the HOME ribbon, then click on the arrow next to the DELETE button, then select DELETE SHEET ROWS in the dropdown menu. No matter the approach it is important to delete the entire row, otherwise Excel will move the values up in that column only, which will alter the dataset. Once you remove all the relevant rows scroll to the bottom of your dataset and ensure the columns are of equal length, if not, you may have accidentally deleted a single cell rather than the entire row.


